### ISSUE TITLE
Instalation on Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by moracarlos** [crossbario/crossbardocs#73]
I'm trying to install crossbar on a Raspberry Pi 3 model B with Raspbian Jessie. There's a problem with a dependency, and appears when I try to run `pip install crossbar`

The error I'm getting is:

```
pi@raspberrypi:~ $ sudo pip install crossbar
Collecting crossbar
  Using cached crossbar-0.13.2-py2.py3-none-any.whl
Invalid requirement: 'pyinotify>=0.9.6; linux in "sys_platform"'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'; linux '"
```

**Comment by oberstet** [comment]
try `sudo pip install -U pip` before

**Comment by oberstet** [comment]
closing, as the Crossbar.io Docs have moved into the Crossbar.io main repo ..
